pipeline {
    agent any
    environment {
//         HARBOR_CREDS = credentials('harbor-creds')
//         K8S_CONFIG = credentials('k8s-jenkins ')
//         HARBOR_HOST = 'harbor.local'
    }
    stages {
        stage('unit test') {
            steps {
                echo 'project build...'
                sh 'mvn -Pk8s clean package -Dmaven.test.skip=true'
            }
        }

        stage('project build') {
            steps {
                echo 'project build...'
                sh 'mvn -Pk8s clean package -Dmaven.test.skip=true'
                stash excludes: '**/build/**', includes: '**', name: 'source'
            }
        }

        stage('docker build') {
            steps {
                unstash 'source'
                echo 'docker build...'
            }
        }

        stage('k8s deploy') {
            steps {
                echo 'k8s deploy...'
                input "Does the k8s environment look ok?"
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}