pipeline {

    agent any

    stages {
        stage('unit test') {
            agent {
                docker {
                    image 'maven:3.8.4-jdk-8'
                    args '-v /Users/anmy/.m2/:/root/.m2'
                }
            }
            steps {
                echo 'project build...'
                sh 'mvn -Pk8s clean test'
            }
        }

        stage('project build') {
            agent {
                docker {
                    image 'maven:3.8.4-jdk-8'
                    args '-v /Users/anmy/.m2/:/root/.m2'
                }
            }
            steps {
                echo 'project build...'
                sh 'mvn -Pk8s clean package -Dmaven.test.skip=true'
                stash excludes: '**/build/**', includes: '**', name: 'source'
            }
        }

        stage('docker build') {
            steps {
                unstash 'source'
                echo 'docker build...'
                dir("${WORKSPACE}/micro-service-server3") {
                    script {
                        docker.withRegistry('https://registry.cn-hangzhou.aliyuncs.com', 'aliyun-registry') {
                            def customImage = docker.build("plantlink/micro-service-server3:${env.BUILD_ID}")
                            customImage.push()
                            customImage.clean()
                        }
                    }
                }
            }
        }

        stage('k8s deploy') {
            steps {
                echo 'k8s deploy...'
                input "Does the k8s environment look ok?"
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}